config/routes.rb
Rails.application.routes.draw do
  resources :examples
  resources :meanings
  resources :vocabularies do
    member do
      get 'start_link_phrase'
      post 'link_phrase'
    end
  end
  resources :related_words do
    member do
      get 'start_add_vocabulary'
      post 'add_vocabulary'
    end
  end
  # get '/related_words/start_add_vocabulary' => "related_word#start_add_vocabulary"
  get '/review' => "review#index",   :as => "review"
  post '/review/remember' => "review#remember"
  post '/review/donot_remember' => "review#donot_remember"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
end

app/models/related_word.rb
class RelatedWord < ApplicationRecord

  has_many :related_word_and_vocabularies
  has_many :vocabularies, :through => :related_word_and_vocabularies

end

app/controllers/related_words_controller.rb
class RelatedWordsController < ApplicationController
  before_action :set_related_word, only: [:show, :edit, :update, :destroy, :start_add_vocabulary, :add_vocabulary]

  # GET /related_words
  # GET /related_words.json
  def index
    @related_words = RelatedWord.all
  end

  # GET /related_words/1
  # GET /related_words/1.json
  def show
  end

  # GET /related_words/new
  def new
    @related_word = RelatedWord.new
  end

  # GET /related_words/1/edit
  def edit
  end

  # POST /related_words
  # POST /related_words.json
  def create
    @related_word = RelatedWord.new(related_word_params)

    respond_to do |format|
      if @related_word.save
        format.html { redirect_to @related_word, notice: 'Related word was successfully created.' }
        format.json { render :show, status: :created, location: @related_word }
      else
        format.html { render :new }
        format.json { render json: @related_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /related_words/1
  # PATCH/PUT /related_words/1.json
  def update
    respond_to do |format|
      if @related_word.update(related_word_params)
        format.html { redirect_to @related_word, notice: 'Related word was successfully updated.' }
        format.json { render :show, status: :ok, location: @related_word }
      else
        format.html { render :edit }
        format.json { render json: @related_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /related_words/1
  # DELETE /related_words/1.json
  def destroy
    @related_word.destroy
    respond_to do |format|
      format.html { redirect_to related_words_url, notice: 'Related word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start_add_vocabulary
  end

  def add_vocabulary
    vocabulary = Vocabulary.find_by_content (params[:vocabulary])
    relation = RelatedWordAndVocabulary.new(
        :related_word => @related_word,
        :vocabulary => vocabulary
    )
    relation.save!
    respond_to do |format|
      format.html { redirect_to @related_word, notice: 'Vocabulary was successfully Added.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_related_word
      @related_word = RelatedWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def related_word_params
      params.require(:related_word).permit(:name)
    end
end

app/helpers/related_words_helper.rb
module RelatedWordsHelper
end

app/views/related_words/_form.html.erb
<%= form_with(model: related_word, local: true) do |form| %>
  <% if related_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(related_word.errors.count, "error") %> prohibited this related_word from being saved:</h2>

      <ul>
      <% related_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/related_words/edit.html.erb
<h1>Editing Related Word</h1>

<%= render 'form', related_word: @related_word %>

<%= link_to 'Show', @related_word %> |
<%= link_to 'Back', related_words_path %>

app/views/related_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Related Words</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @related_words.each do |related_word| %>
      <tr>
        <td><%= related_word.name %></td>
        <td><%= link_to 'Show', related_word %></td>
        <td><%= link_to 'Edit', edit_related_word_path(related_word) %></td>
        <td><%= link_to 'Destroy', related_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Related Word', new_related_word_path %> |
<%= link_to '单词', vocabularies_path %>

app/views/related_words/new.html.erb
<h1>New Related Word</h1>

<%= render 'form', related_word: @related_word %>

<%= link_to 'Back', related_words_path %>

app/views/related_words/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @related_word.name %></h1>

<h3>关联单词：</h3>
<ul>
  <% @related_word.vocabularies.each do |vocabulary| %>
    <li><%= link_to vocabulary.content,vocabulary %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_related_word_path(@related_word) %> |
<%= link_to 'Back', related_words_path %>
<%= link_to "Add Vocabulary", start_add_vocabulary_related_word_path(@related_word) %>

app/views/related_words/start_add_vocabulary.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @related_word.name %></h1>

<form action="/related_words/<%= @related_word.id %>/add_vocabulary" accept-charset="UTF-8" method="post">

  <div class="field">
    <label for="related_word_name">vocabulary</label>
    <input type="text" name="vocabulary" id="vocabulary" />
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Add Vocabulary"/>
  </div>
</form>