config/routes.rb
Rails.application.routes.draw do
  resources :examples
  resources :meanings
  resources :vocabularies do
    member do
      get 'start_link_phrase'
      post 'link_phrase'
    end
  end
  resources :related_words do
    member do
      get 'start_add_vocabulary'
      post 'add_vocabulary'
    end
  end
  # get '/related_words/start_add_vocabulary' => "related_word#start_add_vocabulary"
  get '/review' => "review#index",   :as => "review"
  post '/review/remember' => "review#remember"
  post '/review/donot_remember' => "review#donot_remember"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
end

app/models/example.rb
class Example < ApplicationRecord
  belongs_to :meaning

  before_save :default_values
  def default_values
    self.proficiency ||= 0
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
    @example.meaning = Meaning.find params["meaning_id"]
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        # format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.html { redirect_to @example.meaning, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:meaning_id, :original, :zh_meaning, :meaning_id)
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.erb
<%= form_with(model: example, local: true) do |form| %>
  <% if example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :meaning_id, :value=>@example.meaning.id  %>

  <div class="field">
    <%= form.label :original %>
    <%= form.text_field :original, :style=>'width:800px;' %>
  </div>

  <div class="field">
    <%= form.label :zh_meaning %>
    <%= form.text_field :zh_meaning, :style=>'width:800px;' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Examples</h1>

<table>
  <thead>
    <tr>
      <th>Meaning</th>
      <th>Original</th>
      <th>Zh meaning</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.meaning_id %></td>
        <td><%= example.original %></td>
        <td><%= example.zh_meaning %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meaning:</strong>
  <%= @example.meaning_id %>
</p>

<p>
  <strong>Original:</strong>
  <%= @example.original %>
</p>

<p>
  <strong>Zh meaning:</strong>
  <%= @example.zh_meaning %>
</p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>