config/routes.rb
Rails.application.routes.draw do
  resources :examples
  resources :meanings
  resources :vocabularies do
    member do
      get 'start_link_phrase'
      post 'link_phrase'
    end
  end
  resources :related_words do
    member do
      get 'start_add_vocabulary'
      post 'add_vocabulary'
    end
  end
  # get '/related_words/start_add_vocabulary' => "related_word#start_add_vocabulary"
  get '/review' => "review#index",   :as => "review"
  post '/review/remember' => "review#remember"
  post '/review/donot_remember' => "review#donot_remember"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord

  has_many :meanings

  # 单词与词组关联
  has_many :phrases, class_name: 'Phrase', foreign_key: 'word_id'
  has_many :words, class_name: 'Phrase', foreign_key: 'phrase_id'

  # 单词之间关联
  has_many :related_word_and_vocabularies
  has_many :related_words, :through => :related_word_and_vocabularies

end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  before_action :set_vocabulary, only: [:show, :edit, :update, :destroy, :start_link_phrase, :link_phrase]

  # GET /vocabularies
  # GET /vocabularies.json
  def index
    @vocabularies = Vocabulary.where( :kind => 'word').order("id DESC")
  end

  # GET /vocabularies/1
  # GET /vocabularies/1.json
  def show
  end

  # GET /vocabularies/new
  def new
    @vocabulary = Vocabulary.new
  end

  # GET /vocabularies/1/edit
  def edit
  end

  # POST /vocabularies
  # POST /vocabularies.json
  def create
    @vocabulary = Vocabulary.new(vocabulary_params)

    respond_to do |format|
      if @vocabulary.save
        format.html { redirect_to @vocabulary, notice: 'Vocabulary was successfully created.' }
        format.json { render :show, status: :created, location: @vocabulary }
      else
        format.html { render :new }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabularies/1
  # PATCH/PUT /vocabularies/1.json
  def update
    respond_to do |format|
      if @vocabulary.update(vocabulary_params)
        format.html { redirect_to @vocabulary, notice: 'Vocabulary was successfully updated.' }
        format.json { render :show, status: :ok, location: @vocabulary }
      else
        format.html { render :edit }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabularies/1
  # DELETE /vocabularies/1.json
  def destroy
    @vocabulary.destroy
    respond_to do |format|
      format.html { redirect_to vocabularies_url, notice: 'Vocabulary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start_link_phrase
  end

  def link_phrase
    word_group = Vocabulary.find_by_content (params[:phrase])
    phrase = Phrase.new(
       :word => @vocabulary,
       :word_group => word_group
    )
    phrase.save!
    respond_to do |format|
      format.html { redirect_to @vocabulary, notice: '与#{word_group.content}关联成功' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulary
      @vocabulary = Vocabulary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocabulary_params
      params.require(:vocabulary).permit(:content, :kind, :soundmark)
    end
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/vocabularies/_form.html.erb
<%= form_with(model: vocabulary, local: true) do |form| %>
  <% if vocabulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vocabulary.errors.count, "error") %> prohibited this vocabulary from being saved:</h2>

      <ul>
      <% vocabulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= select( "vocabulary", "kind", { "单词" => "word", "短语" => "phrase"}) %>
  </div>

  <div class="field">
    <%= form.label :soundmark %>
    <%= form.text_field :soundmark %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vocabularies/edit.html.erb
<h1>Editing Vocabulary</h1>

<%= render 'form', vocabulary: @vocabulary %>

<%= link_to 'Show', @vocabulary %> |
<%= link_to 'Back', vocabularies_path %>

app/views/vocabularies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>词汇表</h1>

<%= link_to 'New Vocabulary', new_vocabulary_path %> |
<%= link_to '关联词', related_words_path %> |
<%= link_to 'review', '/review' %>

<table>
  <thead>
    <tr>
      <th>单词</th>
      <th>音标</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vocabularies.each do |vocabulary| %>
      <tr>
        <td><%= vocabulary.content %></td>
        <td><%= vocabulary.soundmark %></td>
        <td><%= link_to 'Show', vocabulary %></td>
        <td><%= link_to 'Edit', edit_vocabulary_path(vocabulary) %></td>
        <td><%= link_to 'Destroy', vocabulary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/vocabularies/new.html.erb
<h1>New Vocabulary</h1>

<%= render 'form', vocabulary: @vocabulary %>

<%= link_to 'Back', vocabularies_path %>

app/views/vocabularies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @vocabulary.content %></h1>

<p style="color:#9b8d72;font-size: 14px;line-height: 24px;">
  <%= @vocabulary.soundmark %>
</p>

<div style="height: 10px;"></div>

<% @vocabulary.meanings.each do |meaning| %>
<p style="margin-bottom: 20px;">
  <a style='border-radius: 50%;text-align: center;line-height: 20px;background: #c1943b;width: 14px;height: 14px;display: inline-block;'></a>
  <span style='line-height: 24px;font-size: 14px;color: #32220e;font-weight: 700;'>
    <%= meaning.en_meaning %><br>
  </span>
  <span style='color:#958d79;font-size: 16px;font-family: arial,sans-serif,"microsoft yahei",simhei;'>
    <%= meaning.kind %>
  </span>
  <span style='line-height: 24px;font-size: 14px;color: #32220e;'>
    <%= meaning.zh_meaning %>
  </span>
  <%= link_to 'New Example', new_example_path(meaning_id:meaning.id), name:'new_example_link', style:'display: none' %>

  <% meaning.examples.each do |example| %>
  <p>
    <span>
      <%= example.original %>
    </span><br>
    <span>
      <%= example.zh_meaning %>
    </span>
  </p>
  <% end %>
</p>
<% end %>

<%= link_to 'Edit', edit_vocabulary_path(@vocabulary) %> |
<%= link_to 'Back', vocabularies_path %> |
<%= link_to 'New Meaning', new_meaning_path(vocabulary_id:@vocabulary.id) %>
<button onclick="show_links()">显示链接</button>
<button onclick="hidden_links()">隐藏链接</button>

<br>
<br>

<% if @vocabulary.kind == 'word' %>
<h3>短句：</h3>
  <%= link_to '关联短句', start_link_phrase_vocabulary_path %>
<ul>
  <% @vocabulary.phrases.each do |phrase| %>
    <li><%= link_to phrase.word_group.content,phrase.word_group %></li>
  <% end %>
</ul>
<% end %>

<% if @vocabulary.kind == 'phrase' %>
<h3>单词：</h3>
<ul>
  <% @vocabulary.words.each do |phrase| %>
    <li><%= link_to phrase.word.content,phrase.word %></li>
  <% end %>
</ul>
<% end %>

<br>
<br>

<h3>相关词：</h3>
<% if @vocabulary.related_words.empty? %>
  <%= link_to '增加相关词', new_related_word_path %>
<% end %>
<ul>
  <% @vocabulary.related_words.each do |related_word| %>
    <% related_word.vocabularies.each do |vocabulary| %>
      <% unless vocabulary.id == @vocabulary.id %>
        <li><%= link_to vocabulary.content,vocabulary %></li>
      <% end %>
    <% end %>
  <% end %>
</ul>

<script>
  function hidden_links(){
      console.info("1")
      $("a[name=new_example_link]").hide()
  }
  function show_links() {
      $("a[name=new_example_link]").show()
  }
</script>

app/views/vocabularies/start_link_phrase.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @vocabulary.content %></h1>

<form action="/vocabularies/<%= @vocabulary.id %>/link_phrase" accept-charset="UTF-8" method="post">

  <div class="field">
    <label for="related_word_name">phrase</label>
    <input type="text" name="phrase" id="phrase" />
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="关联"/>
  </div>
</form>