config/routes.rb
Rails.application.routes.draw do
  resources :examples
  resources :meanings
  resources :vocabularies do
    member do
      get 'start_link_phrase'
      post 'link_phrase'
    end
  end
  resources :related_words do
    member do
      get 'start_add_vocabulary'
      post 'add_vocabulary'
    end
  end
  # get '/related_words/start_add_vocabulary' => "related_word#start_add_vocabulary"
  get '/review' => "review#index",   :as => "review"
  post '/review/remember' => "review#remember"
  post '/review/donot_remember' => "review#donot_remember"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
end

app/models/meaning.rb
class Meaning < ApplicationRecord
  belongs_to :vocabulary
  has_many :examples
end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
  before_action :set_meaning, only: [:show, :edit, :update, :destroy]

  # GET /meanings
  # GET /meanings.json
  def index
    @meanings = Meaning.all
  end

  # GET /meanings/1
  # GET /meanings/1.json
  def show
  end

  # GET /meanings/new
  def new
    @meaning = Meaning.new
    @meaning.vocabulary = Vocabulary.find params["vocabulary_id"]
  end

  # GET /meanings/1/edit
  def edit
  end

  # POST /meanings
  # POST /meanings.json
  def create
    @meaning = Meaning.new(meaning_params)

    logger.info("值得記錄的一般訊息#{@meaning.vocabulary}")

    respond_to do |format|
      if @meaning.save
        format.html { redirect_to @meaning, notice: 'Meaning was successfully created.' }
        #format.html { redirect_to @meaning.vocabulary, notice: 'Meaning was successfully created.' }
        format.json { render :show, status: :created, location: @meaning }
      else
        format.html { render :new }
        format.json { render json: @meaning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meanings/1
  # PATCH/PUT /meanings/1.json
  def update
    respond_to do |format|
      if @meaning.update(meaning_params)
        format.html { redirect_to @meaning, notice: 'Meaning was successfully updated.' }
        format.json { render :show, status: :ok, location: @meaning }
      else
        format.html { render :edit }
        format.json { render json: @meaning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meanings/1
  # DELETE /meanings/1.json
  def destroy
    @meaning.destroy
    respond_to do |format|
      format.html { redirect_to meanings_url, notice: 'Meaning was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meaning
      @meaning = Meaning.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meaning_params
      params.require(:meaning).permit(:kind, :zh_meaning, :en_meaning, :vocabulary, :vocabulary_id)
    end
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/views/meanings/_form.html.erb
<%= form_with(model: meaning, local: true) do |form| %>
  <% if meaning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meaning.errors.count, "error") %> prohibited this meaning from being saved:</h2>

      <ul>
      <% meaning.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :vocabulary_id, :value=>@meaning.vocabulary.id  %>

  <div class="field">
    <%= form.label :kind %>
    <%= select( "meaning", "kind", { "" => "", "noun" => "noun", "verb" => "verb", "adjective" => "adjective", "adverb" => "adverb", "pronoun" => "", "conjunction" => "conjunction"}) %>
  </div>

  <div class="field">
    <%= form.label :en_meaning %>
    <%= form.text_field :en_meaning %>
  </div>

  <div class="field">
    <%= form.label :zh_meaning %>
    <%= form.text_field :zh_meaning %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meanings/edit.html.erb
<h1>Editing Meaning</h1>

<%= render 'form', meaning: @meaning %>

<%= link_to 'Show', @meaning %> |
<%= link_to 'Back', meanings_path %>

app/views/meanings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meanings</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Zh meaning</th>
      <th>En meaning</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meanings.each do |meaning| %>
      <tr>
        <td><%= meaning.kind %></td>
        <td><%= meaning.zh_meaning %></td>
        <td><%= meaning.en_meaning %></td>
        <td><%= link_to 'Show', meaning %></td>
        <td><%= link_to 'Edit', edit_meaning_path(meaning) %></td>
        <td><%= link_to 'Destroy', meaning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meaning', new_meaning_path %>

app/views/meanings/new.html.erb
<h1>New Meaning</h1>

<%= render 'form', meaning: @meaning %>

<%= link_to 'Back', meanings_path %>

app/views/meanings/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @meaning.vocabulary.content %></h1>

<p style="color:#9b8d72;font-size: 14px;line-height: 24px;">
  <%= @meaning.vocabulary.soundmark %>
</p>

<p style="margin-bottom: 20px;">
  <a style='border-radius: 50%;text-align: center;line-height: 20px;background: #c1943b;width: 14px;height: 14px;display: inline-block;'></a>
  <span style='line-height: 24px;font-size: 14px;color: #32220e;font-weight: 700;'>
    <%= @meaning.en_meaning %><br>
  </span>
  <span style='color:#958d79;font-size: 16px;font-family: arial,sans-serif,"microsoft yahei",simhei;'>
    <%= @meaning.kind %>
  </span>
  <span style='line-height: 24px;font-size: 14px;color: #32220e;'>
    <%= @meaning.zh_meaning %>
  </span>

  <% @meaning.examples.each do |example| %>
  <p>
    <span>
      <%= example.original %>
    </span><br>
    <span>
      <%= example.zh_meaning %>
    </span>
  </p>
<% end %>
</p>

<%= link_to 'Edit', edit_meaning_path(@meaning) %> |
<%= link_to 'Back To Vocabulary', @meaning.vocabulary %> |
<%= link_to 'New Example', new_example_path(meaning_id:@meaning.id) %>